# The number of milliseconds of each tick
tickTime: 2000

# The number of ticks that the initial
# synchronization phase can take
initLimit: 10

# The number of ticks that can pass between
# sending a request and getting an acknowledgement
syncLimit: 5

# the directory where the snapshot is stored.
dataDir: /var/lib/zookeeper

# Place the dataLogDir to a separate physical disc for better performance
# dataLogDir=/disk2/zookeeper

# the port at which the clients will connect
clientPort: 2181
